/**
 * unisim_ros2_control_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.22.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Body.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Body_H_
#define IO_SWAGGER_CLIENT_MODEL_Body_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Body
    : public ModelBase
{
public:
    Body();
    virtual ~Body();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Body members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUrdfPath() const;
    bool urdfPathIsSet() const;
    void unsetUrdf_path();
    void setUrdfPath(utility::string_t value);

protected:
    utility::string_t m_Urdf_path;
    bool m_Urdf_pathIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Body_H_ */
