/**
 * unisim_ros2_control_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.22.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Body.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Body::Body()
{
    m_Urdf_path = utility::conversions::to_string_t("");
    m_Urdf_pathIsSet = false;
}

Body::~Body()
{
}

void Body::validate()
{
    // TODO: implement validation
}

web::json::value Body::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_Urdf_pathIsSet)
    {
        val[utility::conversions::to_string_t("urdf_path")] = ModelBase::toJson(m_Urdf_path);
    }

    return val;
}

void Body::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("urdf_path")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("urdf_path")];
        if(!fieldValue.is_null())
        {
            setUrdfPath(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void Body::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_Urdf_pathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("urdf_path"), m_Urdf_path));
        
    }
}

void Body::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("urdf_path")))
    {
        setUrdfPath(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("urdf_path"))));
    }
}

utility::string_t Body::getUrdfPath() const
{
    return m_Urdf_path;
}


void Body::setUrdfPath(utility::string_t value)
{
    m_Urdf_path = value;
    m_Urdf_pathIsSet = true;
}
bool Body::urdfPathIsSet() const
{
    return m_Urdf_pathIsSet;
}

void Body::unsetUrdf_path()
{
    m_Urdf_pathIsSet = false;
}

}
}
}
}

