/**
 * unisim_ros2_control_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.23.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Quaternion.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Quaternion_H_
#define IO_SWAGGER_CLIENT_MODEL_Quaternion_H_


#include "../ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Quaternion
    : public ModelBase
{
public:
    Quaternion();
    virtual ~Quaternion();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Quaternion members

    /// <summary>
    /// 
    /// </summary>
    double getX() const;
    bool XIsSet() const;
    void unsetx();
    void setX(double value);
    /// <summary>
    /// 
    /// </summary>
    double getY() const;
    bool YIsSet() const;
    void unsety();
    void setY(double value);
    /// <summary>
    /// 
    /// </summary>
    double getZ() const;
    bool ZIsSet() const;
    void unsetz();
    void setZ(double value);
    /// <summary>
    /// 
    /// </summary>
    double getW() const;
    bool WIsSet() const;
    void unsetw();
    void setW(double value);

protected:
    double m_x;
    bool m_xIsSet;
    double m_y;
    bool m_yIsSet;
    double m_z;
    bool m_zIsSet;
    double m_w;
    bool m_wIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Quaternion_H_ */
