/**
 * unisim_ros2_control_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.22.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Spawn_request.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Spawn_request_H_
#define IO_SWAGGER_CLIENT_MODEL_Spawn_request_H_


#include "../ModelBase.h"

#include "Pose.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Spawn_request
    : public ModelBase
{
public:
    Spawn_request();
    virtual ~Spawn_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Spawn_request members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUrdfPath() const;
    bool urdfPathIsSet() const;
    void unsetUrdf_path();
    void setUrdfPath(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Pose> getPose() const;
    bool poseIsSet() const;
    void unsetPose();
    void setPose(std::shared_ptr<Pose> value);

protected:
    utility::string_t m_Urdf_path;
    bool m_Urdf_pathIsSet;
    std::shared_ptr<Pose> m_Pose;
    bool m_PoseIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Spawn_request_H_ */
