swagger: '2.0'

info:
  version: "0.0.1"
  title: unisim_ros2_control_api

paths:
  /spawn:
    post:
      summary: spawn robot from URDF
      consumes:
       - multipart/form-data
      produces: 
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            urdf_path:
              type: "string"
              example: "/tmp/robot.urdf"
         
      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string