swagger: '2.0'

info:
  version: "0.0.1"
  title: unisim_ros2_control_api

definitions:
  Point:
    type: object
    properties:
      x:
        type: number
        format: double
        example: 0.0
      y:
        type: number
        format: double
        example: 0.0
      z:
        type: number
        format: double
        example: 0.0
  Quaternion:
    type: object
    properties:
      x:
        type: number
        format: double
        example: 0.0
      y:
        type: number
        format: double
        example: 0.0
      z:
        type: number
        format: double
        example: 0.0
      w:
        type: number
        format: double
        example: 1.0
  Pose:
    type: object
    properties:
      position:
        type: object
        $ref: "#/definitions/Point"
      orientation:
        type: object
        $ref: "#/definitions/Quaternion"

paths:
  /spawn:
    post:
      summary: spawn robot from URDF
      consumes:
       - multipart/form-data
      produces: 
      - "application/json"
      parameters:
      - name: spawn_request
        in: body
        required: true
        schema:
          type: object
          properties:
            urdf_path:
              type: string
              example: "/tmp/robot.urdf"
            pose:
              type: object
              $ref: "#/definitions/Pose"
      responses:
        200:
          description: responses from UniSim
          schema:
            title: result
            properties:
              success:
                type: boolean
  /start:
    post:
      summary: start simulation
      consumes:
       - multipart/form-data
      produces: 
      - "application/json"
      parameters:
      - name: start_simulation_request
        in: body
        schema:
          type: object
          properties:
            realtime_factor:
              type: number
              default: 1.0
              format: double
      responses:
        200:
          description: responses from UniSim
          schema:
            title: result
            properties:
              success:
                type: boolean
  /stop:
    post:
      summary: stop simulation
      consumes:
       - multipart/form-data
      produces: 
      - "application/json"
      responses:
        200:
          description: responses from UniSim
          schema:
            title: result
            properties:
              success:
                type: boolean